//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CircusAlina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repertoire
    {
        public int RepertoireID { get; set; }
        public Nullable<int> ShowID { get; set; }
        public Nullable<System.DateTime> PerformanceDate { get; set; }
    
        public virtual Shows Shows { get; set; }
    }
}
