//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CircusAlina
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketSales
    {
        public int SaleID { get; set; }
        public Nullable<int> TicketID { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Tickets Tickets { get; set; }
    }
}
